CC=gcc
INCLUDIR = ./include

all:
#	gcc register.c -o register `pkg-config --cflags --libs gtk+-2.0`
	gcc ./src/*.c -o login -I./include `pkg-config --cflags --libs gtk+-2.0` 
#	gcc main.c -o main `pkg-config --cflags --libs gtk+-2.0`
#	gcc new.c -o new `pkg-config --cflags --libs gtk+-2.0`



